# BASE UI
ColorColumn: '- separated'
Conceal: ''
Cursor: ''
CursorIM: ''
CursorColumn: '- separated'
CursorLine: '- separated'
CursorLineNr: 'blue2 - '
Directory: 'blue3 -'
DiffAdd: '- green4'
DiffChange: '- blue4'
DiffDelete: 'red1 red4'
DiffText: '- blue4 bi'
ErrorMsg: 'red1 - r'
VertSplit: ''
Folded: 'grey2 dimmed'
FoldColumn: 'grey2 dimmed'
SignColumn: '-  separated'
IncSearch: '- - bu'
LineNr: 'grey3 -'
MatchParen: 'red1 - b'
ModeMsg: ''
MoreMsg: ''
NonText: 'grey3 -'
Normal: 'text bg'
PMenu: 'bg blue1'
PMenuSel: 'bg green1'
PmenuSbar: 'yellow1 yellow1'
PmenuThumb: 'yellow2 yellow2'
Question: 'green1 -'
Search: '- yellow4'
SpecialKey: 'blue2'
SpellBad: 'red1'
SpellLocal: 'yellow1'
SpellCap: 'yellow2'
SpellRare: 'blue2'
StatusLine: 'bg blue2 b'
StatusLineNC: 'bg grey2 b'
TabLine: 'bg grey3'
TabLineFill: '- grey3'
TabLineSel: 'bg blue2 b'
Title: 'blue3 - b'
Visual: '- highlighted'
VisualNOS: '- highlighted'
WarningMsg: 'red1 -'
WildMenu: 'bg green1 b'
Comment: 'grey2 - i'
Constant: 'yellow2 -'
String: 'yellow1 -' # Constant
Character: 'yellow2 -' # Constant
Boolean: 'yellow2 -' # Constant
Number: 'yellow2 -' # Constant
Float: 'yellow2 -' # Constant
Identifier: 'blue3 -'
Function: 'blue3 -' # Identifier
Statement: 'blue3 -'
Conditional: 'green2 -' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: 'red1 -' # Statement
Keyword: '' # Statement
Exception: 'red1 -' # Statement
PreProc: 'green1 -'
Include: '' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'blue2 - '
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: 'blue2 -'
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: '- - u'
Ignore: ''
Error: 'text red1'
Todo: 'red1 - b'



